version: '3.1'

services:
  db:
    image: mysql:5.7.12
    restart: always
    container_name: mysql5
    ports:
      - 6603:3306    
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - C:\Workspace\mysql\data:/var/lib/mysql
      - C:\Workspace\mysql\conf.d:/etc/mysql/conf.d